var res = {
    StartNormal_png : "res/start_game0.png",
    StartSelected_png : "res/start_game1.png",
    Heart0_png: "res/heart.png",
    Heart1_png: "res/heart1.png",
    Screen_png : "res/galaxy.png",
    NoteRed_png : "res/note/NoteRed.png",
    NoteOrange_png : "res/note/NoteOrange.png",
    NoteYellow_png : "res/note/NoteYellow.png",
    NoteGreen_png : "res/note/NoteGreen.png",
    NoteBlue_png : "res/note/NoteBlue.png",
    NoteViolet_png : "res/note/NoteViolet.png",
    Bg_png: "res/bg.png",
    HighScore0_png: "res/high_score0.png",
    HighScore1_png: "res/high_score1.png",
    Back0_png: "res/back0.png",
    Back1_png: "res/back1.png",
    Again0_png: "res/play_again0.png",
    Again1_png: "res/play_again1.png",
    Confirm0_png: "res/key/Confirm0.png",
    Confirm1_png: "res/key/Confirm1.png",
    Admin0_png: "res/Admin0.png",
    Admin1_png: "res/Admin1.png",
    Ba_png: "res/ba.png",
    Start_png: "res/status/Start.png",
    Play_png: "res/status/Play.png",
    Do_mp3: "sound/Do1.mp3",
    Ra_mp3: "sound/Ra1.mp3",
    Me_mp3: "sound/Me1.mp3",
    Fa_mp3: "sound/Fa1.mp3",
    Sol_mp3: "sound/Sol1.mp3",
    La_mp3: "sound/La1.mp3",
    Red1_png: "res/press/red1.png",
    Red2_png: "res/press/red2.png",
    Orange1_png: "res/press/orange1.png",
    Orange2_png: "res/press/orange2.png",
    Yellow1_png: "res/press/yellow1.png",
    Yellow2_png: "res/press/yellow2.png",
    Green1_png: "res/press/green1.png",
    Green2_png: "res/press/green2.png",
    Blue1_png: "res/press/blue1.png",
    Blue2_png: "res/press/blue2.png",
    Violet1_png: "res/press/violet1.png",
    Violet2_png: "res/press/violet2.png",
    spUp_png: "res/item/speed-up.png",
    spDown_png: "res/item/speed-down.png",
    hlUp_png: "res/item/health.png",
    keyX_png: "res/item/key00.png",
    keyY_png: "res/item/key01.png",
    keyZ_png: "res/item/key02.png",
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}