var res = {
    StartNormal_png : "res/start_game0.png",
    StartSelected_png : "res/start_game1.png",
    Heart0_png: "res/heart.png",
    Heart1_png: "res/heart1.png",
    Screen_png : "res/galaxy.png",
    NoteRed_png : "res/note/NoteRed.png",
    NoteOrange_png : "res/note/NoteOrange.png",
    NoteYellow_png : "res/note/NoteYellow.png",
    NoteGreen_png : "res/note/NoteGreen.png",
    NoteBlue_png : "res/note/NoteBlue.png",
    NoteViolet_png : "res/note/NoteViolet.png",
    LightRed_png : "res/note/LightRed.png",
    LightOrange_png : "res/note/LightOrange.png",
    LightYellow_png : "res/note/LightYellow.png",
    LightGreen_png : "res/note/LightGreen.png",
    LightBlue_png : "res/note/LightBlue.png",
    LightViolet_png : "res/note/LightViolet.png",
    Bg_png: "res/bg.png",
    HighScore0_png: "res/high_score0.png",
    HighScore1_png: "res/high_score1.png",
    Back_png: "res/back.png",
    Back0_png: "res/back0.png",
    Back1_png: "res/back1.png",
    Again0_png: "res/play_again0.png",
    Again1_png: "res/play_again1.png",
    Confirm0_png: "res/key/Confirm0.png",
    Confirm1_png: "res/key/Confirm1.png",
    Admin0_png: "res/Admin0.png",
    Admin1_png: "res/Admin1.png",
    Ba_png: "res/ba.png",
    Start_png: "res/status/Start.png",
    Play_png: "res/status/Play.png",
    Do_mp3: "sound/Do1.mp3",
    Ra_mp3: "sound/Ra1.mp3",
    Me_mp3: "sound/Me1.mp3",
    Fa_mp3: "sound/Fa1.mp3",
    Sol_mp3: "sound/Sol1.mp3",
    La_mp3: "sound/La1.mp3",
    Red1_png: "res/press/red1.png",
    Red2_png: "res/press/red2.png",
    Orange1_png: "res/press/orange1.png",
    Orange2_png: "res/press/orange2.png",
    Yellow1_png: "res/press/yellow1.png",
    Yellow2_png: "res/press/yellow2.png",
    Green1_png: "res/press/green1.png",
    Green2_png: "res/press/green2.png",
    Blue1_png: "res/press/blue1.png",
    Blue2_png: "res/press/blue2.png",
    Violet1_png: "res/press/violet1.png",
    Violet2_png: "res/press/violet2.png",
    spUp_png: "res/item/speed-up.png",
    spDown_png: "res/item/speed-down.png",
    hlUp_png: "res/item/health.png",
    keyX_png: "res/item/key00.png",
    keyY_png: "res/item/key01.png",
    keyZ_png: "res/item/key02.png",
    Perfect_png: "res/action/perfect.png",
    Miss_png: "res/action/miss.png",
    keyQ0_png: "res/key/Q0.png",
    keyA0_png: "res/key/A0.png",
    keyZ0_png: "res/key/Z0.png",
    keyW0_png: "res/key/W0.png",
    keyS0_png: "res/key/S0.png",
    keyX0_png: "res/key/X0.png",
    keyE0_png: "res/key/E0.png",
    keyD0_png: "res/key/D0.png",
    keyC0_png: "res/key/C0.png",
    keyR0_png: "res/key/R0.png",
    keyF0_png: "res/key/F0.png",
    keyV0_png: "res/key/V0.png",
    keyT0_png: "res/key/T0.png",
    keyG0_png: "res/key/G0.png",
    keyB0_png: "res/key/B0.png",
    keyY0_png: "res/key/Y0.png",
    keyH0_png: "res/key/H0.png",
    keyN0_png: "res/key/N0.png",
    keyU0_png: "res/key/U0.png",
    keyJ0_png: "res/key/J0.png",
    keyM0_png: "res/key/M0.png",
    keyI0_png: "res/key/I0.png",
    keyK0_png: "res/key/K0.png",
    keyO0_png: "res/key/O0.png",
    keyL0_png: "res/key/L0.png",
    keyP0_png: "res/key/P0.png",
    keyEN0_png: "res/key/Enter0.png",
    keyDE0_png: "res/key/Delete0.png",
    keyUP0_png: "res/key/up0.png",
    keyDOWN0_png: "res/key/down0.png",
    keyQ1_png: "res/key/Q1.png",
    keyA1_png: "res/key/A1.png",
    keyZ1_png: "res/key/Z1.png",
    keyW1_png: "res/key/W1.png",
    keyS1_png: "res/key/S1.png",
    keyX1_png: "res/key/X1.png",
    keyE1_png: "res/key/E1.png",
    keyD1_png: "res/key/D1.png",
    keyC1_png: "res/key/C1.png",
    keyR1_png: "res/key/R1.png",
    keyF1_png: "res/key/F1.png",
    keyV1_png: "res/key/V1.png",
    keyT1_png: "res/key/T1.png",
    keyG1_png: "res/key/G1.png",
    keyB1_png: "res/key/B1.png",
    keyY1_png: "res/key/Y1.png",
    keyH1_png: "res/key/H1.png",
    keyN1_png: "res/key/N1.png",
    keyU1_png: "res/key/U1.png",
    keyJ1_png: "res/key/J1.png",
    keyM1_png: "res/key/M1.png",
    keyI1_png: "res/key/I1.png",
    keyK1_png: "res/key/K1.png",
    keyO1_png: "res/key/O1.png",
    keyL1_png: "res/key/L1.png",
    keyP1_png: "res/key/P1.png",
    keyEN1_png: "res/key/Enter1.png",
    keyDE1_png: "res/key/Delete1.png",
    keyUP1_png: "res/key/up1.png",
    keyDOWN1_png: "res/key/down1.png",
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}